name: Deploy Backend (NestJS) to EC2

on:
  push:
    paths:
      - 'g5-chatapp-be/**'            # Chỉ chạy khi có thay đổi trong thư mục be
    branches:
      - main               # Hoặc branch bạn muốn deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: g5-chatapp-be   # Tất cả các bước `run` thực hiện trong thư mục /be

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./g5-chatapp-be
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest

      - name: Copy SSH Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest
            docker stop nestjs-app || true
            docker rm nestjs-app || true
            docker run -d -p 3000:3000 --name nestjs-app ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest
          EOF
